### ISSUE TITLE
Cannot connect to mysql when password is quoted

### ISSUE THREAD

**Issue by tersmitten** [jzawodn/mytop#17]
```
# mytop 
Cannot connect to MySQL server. Please check the:

  * database you specified "" (default is "")
  * username you specified "root" (default is "root")
  * password you specified "'foo'" (default is "")
  * hostname you specified "localhost" (default is "localhost")
  * port you specified "3306" (default is 3306)
  * socket you specified "" (default is "")

The options my be specified on the command-line or in a ~/.mytop or
~/.my.cnf config file. See the manual (perldoc mytop) for details.

Here's the exact error from DBI. It might help you debug:

Access denied for user 'root'@'localhost' (using password: YES)
```

`mytop` should trim quotes from the password

**Comment by tersmitten** [comment]
Any update on this?

**Comment by reinierpost** [comment]
1) Why is this a problem? Omit the quotes yourself.
2) I don't think jzawodny is still working on mytop. There are several clones with further development here on GitHub.  It would be nice if they can be unified.

**Comment by tersmitten** [comment]
> Why is this a problem? Omit the quotes yourself.

That's not always possible, for instance when your password contains `$`, [see](http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html)

**Comment by reinierpost** [comment]
I believe you're misunderstanding your problem.

First of all, this has nothing to do with `bash`.  `mytop` is a Perl script and it reads its configuration file using Perl code.

Second, it is true that the present code excludes certain valid MySQL passwords: [a pending pull request](https://github.com/jzawodn/mytop/pull/8) fixes the bug that `=` characters cannot appear.  However, as far as I can see, quotes work just fine.

Why is mytop not accepting your MySQL password? I believe it is because you are specifying it with quotes that aren't actually in there.  Your password isn't `'foo'`, it is `foo`.  So write that.

Why are you specifying those quotes? When specifying the MySQL password on the bash command line (as in `mysql -u user -p 'password' ...` it can be necessary to quote it in order to prevent `bash` from interpreting characters in the password that are special to `bash`.  But you don't need to do that here - the password in the `mytop` configuration file is never used on a `bash` command line.

**Comment by tersmitten** [comment]
It uses my `.my.cnf`, which contains quotes.

http://stackoverflow.com/a/19913912/138779

**Comment by reinierpost** [comment]
No, it doesn't use .my.cnf. Look at [the code](https://github.com/jzawodn/mytop/blob/master/mytop)!

**Comment by reinierpost** [comment]
Well, apparently the Debian maintainer has patched mytop to read my.cnf. I just installed it on Ubuntu (a Debian derivative), and indeed it does. So the bug you're reporting is against the Debian version, or a further modification of it, not this original; it fact [it looks like it has been reported already](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845225).

**Comment by tersmitten** [comment]
@reinierpost OK, thanks for your investigation
